[project]
name = "stuart-api"
version = "0.1.0"
description = "Stuart Meme Manager API"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.2",
    "loguru>=0.7.3",
    "pydantic-settings>=2.10.1",
    "supabase>=2.19.0",
    "pillow>=10.0.0",
    "python-multipart>=0.0.6",
    "isort>=6.0.1",
    "redis>=5.0.0",
]

[dependency-groups]
dev = [
    "archpython-cli",
    "black>=25.9.0",
    "pyright>=1.1.405",
    "ruff>=0.13.1",
    "taskipy>=1.14.1",
]

[tool.taskipy.tasks]
lint = "ruff check src --fix && black src && isort src"
typecheck = "pyright src"
run_dev = "fastapi dev src/main.py"

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["stuart-api"]
combine_as_imports = true

[tool.uv.sources]
archpython-cli = { git = "https://github.com/Filipi1/archpython-cli" }

