from typing import Annotated

from fastapi import Depends

from modules.meme.services.domain.increase_meme_to_user_service import IncreaseMemeToUserDomainService
from modules.user.providers.get_user_by_token_service_provider import GetUserByTokenServiceProvider
from modules.meme.providers.earned_memes_repository_provider import EarnedMemesRepositoryProvider


def increase_meme_to_user_domain_provider(get_user_by_token: GetUserByTokenServiceProvider, earned_meme_repository: EarnedMemesRepositoryProvider):
    return IncreaseMemeToUserDomainService(get_user_by_token, earned_meme_repository)


IncreaseMemeToUserDomainServiceProvider = Annotated[
    IncreaseMemeToUserDomainService, Depends(increase_meme_to_user_domain_provider)
]
