apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-api-pull-es
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-stuart-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: ghcr-api-pull
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{\"auths\":{\"ghcr.io\":{\"username\":\"{{ .GHCR_USERNAME }}\",\"password\":\"{{ .GHCR_PASSWORD }}\",\"auth\":\"{{ (printf \"%s:%s\" .GHCR_USERNAME .GHCR_PASSWORD) | b64enc }}\"}}}"
  data:
    - secretKey: GHCR_USERNAME
      remoteRef:
        key: GHCR_USERNAME
    - secretKey: GHCR_PASSWORD
      remoteRef:
        key: GHCR_PASSWORD
